### ISSUE TITLE
Where do the PKGBUILDs for the provided packages reside?

### ISSUE THREAD

**Issue by valorekhov** [OpenVoiceOS/ovos-arch-repo#1]
@JarbasAl 
I see plenty of packages, but only 1 PKGBUILD. 
I've been working on a similar effort [here](https://github.com/valorekhov/ovos-arch-linux) converting some core OVOS buildroot packages, which is still WIP. Would it be possible to take a look a the PKGBUILDs used in this repo?
Thanks!

**Comment by JarbasAl** [comment]
we have automations here to auto generate them https://github.com/OpenVoiceOS/ovos-binary-shop

**Comment by ChanceNCounter** [comment]
Please don’t publish the assistant. We don’t want an influx of users yet.

**Comment by valorekhov** [comment]
> Please don’t publish the assistant. We don’t want an influx of users yet.

Not sure if this one is directed to me. However, at this stage I should be so lucky to be able to distribute a fully-packaged assistant. Still working through being able to run the Core.

@JarbasAl 
Thanks for pointing to the source. This will save me some time.
